import { useMemo } from 'react'
import { buildAnchorStyles } from 'css-anchor-kit'

/**
 * Flip-on-overflow **inside a frame**.
 *
 * Native `position-try` (flip) is judged against the *viewport*, never an inner
 * scroll container — so a floating element won't flip when you scroll a normal
 * `overflow: auto` box. The way to get a framed flip boundary is to make the
 * frame an actual `<iframe>`: the iframe has its *own* viewport, so the kit's
 * emitted CSS flips natively at the iframe's edge as you scroll inside it.
 *
 * The iframe's CSS is generated by the real {@link buildAnchorStyles} so this
 * is the library's own output flipping — nothing bespoke.
 */

const toCss = (o: Record<string, string | number>) =>
  Object.entries(o)
    .map(([k, v]) => `${k.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase())}: ${v}`)
    .join('; ')

export function FlipFrameDemo() {
  const srcDoc = useMemo(() => {
    // placement: 'top' so scrolling DOWN lifts the anchor toward the frame's top
    // edge — when there's no room above, the engine flips it below. Starts in the
    // un-flipped (above) state so there's a clean transition, no fallback sticking.
    const { anchor, floating } = buildAnchorStyles('--frame-flip', {
      placement: 'top',
      offset: 8,
      flip: true,
      strategy: 'fixed',
    })
    return `<!doctype html><html><head><meta charset="utf-8"><style>
      html,body{margin:0}
      body{font:13px ui-sans-serif,system-ui,sans-serif;color:#e8eaf2;background:#0e1019}
      .hint{position:fixed;top:8px;left:0;right:0;text-align:center;font-size:11px;color:#99a0b5;pointer-events:none}
      .top{height:120px}
      .bot{height:560px}
      .a{${toCss(anchor)};width:130px;height:32px;margin:0 auto;display:grid;place-items:center;
         background:linear-gradient(100deg,#8b7dff,#59c2ff);color:#0a0b10;border-radius:7px;font-weight:600}
      .f{${toCss(floating)};width:170px;padding:10px 12px;background:#11141c;color:#e8eaf2;
         border:1px solid #8b7dff;border-radius:8px;box-shadow:0 14px 34px rgba(0,0,0,.55)}
    </style></head><body>
      <div class="hint">↓ scroll inside this frame — it flips at the edge</div>
      <div class="top"></div>
      <div class="a">anchor</div>
      <div class="f">I flip at the frame edge</div>
      <div class="bot"></div>
    </body></html>`
  }, [])

  return (
    <div className="flip-frame-demo">
      <iframe className="flip-frame" srcDoc={srcDoc} title="flip on overflow inside an iframe" />
      <p className="pg-note" style={{ textAlign: 'left' }}>
        This box is an <code>&lt;iframe&gt;</code>, so it has its own viewport —
        the flip boundary the CSS engine actually looks at. Scroll inside it and
        the kit&apos;s emitted <code>position-try-fallbacks</code> flips the
        floating element at the frame edge. Still zero positioning JS.
      </p>
    </div>
  )
}
